### ISSUE TITLE
The return value of randomPrime() and isPrime() are not correct

### ISSUE THREAD

**Issue by hobeas** [Prabhakar-Poudel/random-prime#22]
```js
const { randomPrime, isPrime } = require('random-prime')
const x = randomPrime() // 4678117
isPrime(x) // true
```
But 4678117 is not prime
4678117 = 31 * 150907

**Comment by freddyheppell** [comment]
I noticed this library was broken a while ago and made a fork. I did think the problem had been fixed, but actually it looks like the fix wasn't properly applied.

The issue lies [with this line](https://github.com/Prabhakar-Poudel/random-prime/blob/b7657379e0bdf7d4e387716612fe0166cfeddc19/index.js#L13), which reads:

```js
if (number % i === 0 || number % i + 2 === 0) return false
```

It should instead be:

```js
if (number % i === 0 || number % (i + 2) === 0) return false

```

If you need this fixed urgently, you can use [my fork](https://www.npmjs.com/package/@freddyheppell/random-prime), which is deprecated but is still fine to use until this bug has been fixed here.

**Comment by hobeas** [comment]
Thank you, but there are still some questions
```js
const { isPrime } = require('random-prime')
isPrime(10 / 4) // true
```
2.5 is not prime. I need to enter the calculated number, decimals are inevitable

**Comment by freddyheppell** [comment]
Ah I didn't consider adding a check for integers when I forked it. I'd suggest checking for integers yourself (with `Number.isInteger(x)`) before you call the `isPrime()` method. Ideally this library should be updated for that too.

**Comment by hobeas** [comment]
I wrote a function myself and use the `bignumber.js` module. Because JS Number will be invalid when x is greater than 2^53.

**Comment by freddyheppell** [comment]
@Prabhakar-Poudel There are still 2 unresolved issues from this thread (`i%2` isn't in brackets, and it doesn't say non-integers aren't prime)

**Comment by Prabhakar-Poudel** [comment]
Thank you both, looks like a bug.
@hobeas Should be fixed soon.
